
# META YAML

{% set name = "emews-r" %}
# See README for version meanings:
{% set version = "6" %}

package:
  name:    {{ name }}
  version: {{ version }}

source:
  # R_SVN is exported by conda-build.sh
  path: {{ environ.get('R_SVN', 'UNSET_R_SVN') }}

build:
  number: 1
  # Environment variables for build.sh must be listed here,
  # normal environment inheritance does not happen!
  script_env:
    - PLATFORM={{ environ.get('PLATFORM', 'UNSET_PLATFORM') }}
    - CONFIG_ONLY={{ environ.get('CONFIG_ONLY', '0') }}
    - GITHUB_ACTIONS

# Remember to sync any dependency changes here with conda-install.sh
requirements:
  build:
    - libcurl
    - pcre2
    - xz
    - gfortran
    - zlib
    - xorg-libx11 # xorg-x11-proto-devel
    - xorg-xorgproto
    - xorg-libxt  # For X11/Intrinsic.h
    - libiconv  # For iconv.h
    - cairo
    # For Python 3.9.7, try clang-16, clangxx(15.0.7)
    # try clang-14,15,16 did not work (duplicate LC_RPATH issue)
    - {{ environ.get('CLANG_NAME', 'UNSET_CLANG_NAME') }}
    - clangxx
    # cctools: internal dependency
    # For compile-time error when installing R package 'lattice'
    # Updates Anaconda package 'ld64' to later than 2025-04-01
    # Cf. https://fenicsproject.discourse.group/t/duplicate-lc-rpath-errors-on-macos-15-4-sequoia/17364/6
    #     https://github.com/emews/EMEWS_Issues/issues/65
    #     https://github.com/emews/EMEWS_Issues/issues/77
    # 2025-05-12
    - cctools==1010.6
    # Try ncurses

  run:
    - libcurl
    - pcre2
    - xz
    - gfortran
    - zlib
    - xorg-libx11 # xorg-x11-proto-devel
    - xorg-xorgproto
    - xorg-libxt  # For X11/Intrinsic.h
    - libiconv  # For iconv.h
    - cairo
    - {{ environ.get('CLANG_NAME', 'UNSET_CLANG_NAME') }}
    # See comment above
    - cctools==1010.6
    - clangxx

test:
  files:
    - ./meta-test.sh
  commands:
    - pwd
    - ./meta-test.sh

about:
  home: https://github.com/emews/emews-r-base
  license: Apache License 2.0
  summary: EMEWS build for R

extra:
  recipe-maintainers:
    - swift-t
